#!/bin/bash
#Aslan Oztreves
#10/10/2016


read -p "Do you want to see the script as it executes? (y/[n]) => " debugOn
if [ "$debugOn" == "y" -o "$debugOn" == "Y" ] ; then
	set -x		# very useful switch to the set command
fi
#Variables
a=0    
b=0 
c=0
d=0

for filename in * 
	do
		if [ $filename = "squash" ] ; then
			a=1
			echo "a"
		fi	
		if [ $filename = "sign.c" ] ; then
			b=2
			echo "b"
		fi
#		if [ $filename = "squash.awk" ] ; then
#			c=4
#			echo "c"
#		fi
		
done
	
	#sumofNum=$[a+b+c]
   #echo "$sumofNum"
	if [ $a != 1 ]	; then
		echo "You are missing 'squash' file"
	fi
	if [ $b != 2 ] ; then
		echo "You are missing the 'sign.c' file."
	fi
#	if [ $c	!= 4 ] ; then
#		echo "You are missing the 'squash.awk' file."
#	fi

#Creating Files
gcc -osign sign.c
echo "awk -f squash.awk" > squash	
chmod 700 squash
#Calling Functions

./sign < /usr/share/dict/words | sort | ./squash > out
awk '{ print NF " " $0}' < out | sort -n | tail




