#!/bin/bash
#Aslan Oztreves
#10/13/2016


read -p "Do you want to see the script as it executes? (y/[n]) => " debugOn
if [ "$debugOn" == "y" -o "$debugOn" == "Y" ] ; then
   set -x      # very useful switch to the set command
fi


ARCHIVE=$(find -iname '\archive')

counter=0

for files in $ARCHIVE/*/*
   do
		#Getting the name who send it
      if [ -f "$files" ] ; then
         to=$(sed -n '3'p $files)
         lines=$(cut -c 5- <<< "$to")
         name=${lines//@*}
			#Writing to a new file in order to access it later.
			echo "$name" >> adress.txt
      fi
done

totalnumber=0
#Sorting the file with how many emails they sent
sort adress.txt | uniq -dc >> adress2.txt
sort adress.txt | uniq -uc >> adress2.txt

cat adress2.txt | while read line
do
	#Getting the name and the number change places because sort prints it out
	#number first then name
	nname=$(cut -d ' ' -f 2 <<< "$line")
	number=${line//$nname}
	echo -n "$nname " >> adress3.txt
	echo "$number" >> adress3.txt
	#This was extra where it calculates the total number of emails sent by
	#everyone
	totalnumber=$(( $totalnumber + $number ))
	
	
done
#Sorting according to the number of emails in a decending order
sort -k2 -nr adress3.txt >> adress4.txt
cat adress4.txt | while read line
do 
#Printing one's name with how many email they sent
	echo "$line"
done
#Calculating the total number of different people
tns=$(wc -l adress4.txt)
totalName=${tns// adress4.txt}
echo -n "total "
echo "$totalName"


rm adress.txt
rm adress2.txt
rm adress3.txt
rm adress4.txt
