#!/bin/bash
#Aslan Oztreves
#09/30/2016

read -p "Do you want to see the script as it executes? (y/[n]) => " debugOn
if [ "$debugOn" == "y" -o "$debugOn" == "Y" ] ; then
	set -x		# very useful switch to the set command
fi

if [ $# !=  2 ] ; then
 
	echo "This is an invalid input. You must put two variables."

	exit 99
fi
#Variables

firstExtension=$1
secondExtension=$2
fileDirectory="$PWD"
#Function

for filename in *$firstExtension;
   do
		#if [ $firstExtension != "." ] ; then	
		if grep -q . "$firstExtension" ; then
			echo "success ."	
			InitialName=$(basename "$filename" )
			OnlyFileName=$(echo $InitialName | cut -f 1 -d ".") 
			mv "$InitialName" "${OnlyFileName%$secondExtension}$secondExtension"
		else
			echo "succes harf"
			InitialName=$(basename "$filename" )
         OnlyFileName=${InitialName%$firstExtension*}
         mv "$InitialName" "${OnlyFileName%$secondExtension}$secondExtension"
		fi





	#	InitialName=$(basename "$filename" )	
	#	OnlyFileName=$(echo $InitialName | cut -f 1 -d ".")
	#	mv "$InitialName" "$OnlyFileName$secondExtension" $fileDirectory
done
